version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9393"
    env_file:
      - csvserver.env
    volumes:
      - /home/ubuntu/getting-started-app/inputFile:/csvserver/inputdata
    restart: unless-stopped
